### ISSUE TITLE
Breaking with Meteor 1.4 (Need fourseven:scss Update)

### ISSUE THREAD

**Issue by guns2410** [themeteorchef/bert#28]
The package fails with Meteor 1.4. We need to update fourseven:scss to the latest version

Here is the error log:

```
$ meteor add themeteorchef:bert
 => Errors while adding packages:

While loading package fourseven:scss@3.3.3_3:
error: Command failed:
/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-beta.13.171ccot++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/gunjansoni/.meteor/packages/fourseven_scss/.3.3.3_3.612jqu++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/compileScssBatch/node_modules/.temp-1bggx7y/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 16.0.0
npm ERR! argv
"/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-beta.13.171ccot++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-beta.13.171ccot++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/gunjansoni/.meteor/packages/fourseven_scss/.3.3.3_3.612jqu++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/compileScssBatch/node_modules/.temp-1bggx7y/npm-debug.log
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/gunjansoni/.meteor/packages/fourseven_scss/.3.3.3_3.612jqu++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/compileScssBatch/node_modules/.temp-1bggx7y/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 16.0.0
npm ERR! argv
"/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-beta.13.171ccot++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-beta.13.171ccot++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/gunjansoni/.meteor/packages/fourseven_scss/.3.3.3_3.612jqu++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/compileScssBatch/node_modules/.temp-1bggx7y/npm-debug.log
```

**Comment by hamedhemmati** [comment]
This has stopped working for me as well. I am on meteor 1.3.5.1 with the same error message.

**Comment by guns2410** [comment]
@hamedhemmati you need to have the most recent version of fourseven:scss. If you are using a package that has a specific version of fourseven:scss like the one I was using (themeteorchef:bert) the package owner needs to update the fourseven:scss version and the error would be gone.

**Comment by themeteorchef** [comment]
Just bumped this, should be working now :)

**Comment by mperkh** [comment]
@themeteorchef Is it possible to do that again for fourseven:scss 4.5.0?

**Comment by themeteorchef** [comment]
@mperkh possibly, is there something specific/urgent in the 4.5.0 release? Bert is in the midst of a refactor to move to NPM.

**Comment by mperkh** [comment]
@themeteorchef Its primary for the convenient to not have an
```
The following top-level dependencies were not updated to the very latest version available:
 * fourseven:scss 3.13.0 (4.5.0 is available)
 ```
message, when issuing `meteor update`.

**Comment by themeteorchef** [comment]
@guns2410 just bumped. Check the 2.1.2 release.
