### ISSUE TITLE
Install Fails Win 10

### ISSUE THREAD

**Issue by JackMcK** [themeteorchef/bert#50]
I get the following error installing Meteor on Win 10.  Any suggestions?

C:\Users\jackd\testproject\CCCMMS-master>meteor
[[[[[ C:\Users\jackd\testproject\CCCMMS-master ]]]]]

=> Started proxy.
=> Meteor 1.4.4.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.

C:\Users\jackd\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: No metadata files found for isopack at: /C/Users/jackd/AppData/Local/.meteor/packages/fourseven_scss/3.3.3_3
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:879:13)
    at C:\tools\packaging\tropohouse.js:500:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\jackd\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:499:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23

**Comment by themeteorchef** [comment]
It looks like Bert needs to be updated. Try running `meteor add themeteorchef:bert@2.1.2` in your terminal. This should update the `fourseven:scss` package that seems to be triggering this error.

**Comment by cleverbeagle** [comment]
@JackMcK updated Bert the other day, can you try to pull the latest version and see if this error is corrected?
